name: Debug Mode Tests
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  ducklake-config-tests:
    name: DuckLake (Debug)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['linux_amd64']
        vcpkg_version: [ '2023.04.15' ]
        include:
          - arch: 'linux_amd64'
            vcpkg_triplet: 'x64-linux'

    env:
      VCPKG_TARGET_TRIPLET: ${{ matrix.vcpkg_triplet }}
      GEN: Ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      DISABLE_EXTENSIONS_FOR_TEST: ON

    steps:
    - name: "node-cleanup"
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune -a

    - name: Install required ubuntu packages
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq build-essential cmake ninja-build ccache python3

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Checkout DuckDB to version
      run: |
        cd duckdb
        git checkout $(cat ../.github/duckdb-version)

    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb-postgres' }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b
        vcpkgJsonGlob: './vcpkg.json'

    - name: Build extension
      env:
        GEN: ninja
        CMAKE_BUILD_PARALLEL_LEVEL: 2
      run: |
        make debug

    - name: Test extension
      run: |
        build/debug/test/unittest
